version: '3'

services:
  custom-drupal:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - '8080:80'
    volumes:
      - drupal-mods:/var/www/html/modules
      - drupal-profs:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites/var/www/html/sites
    restart: always
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
   drupal-data:
   drupal-mods:
   drupal-profs:
   drupal-themes:
   drupal-sites:
