version: '3.1'

services:
  drupal:
    image: drupal:8.2
    ports: 
      - 8080:80
    volumes:
      - drupal-mods:/var/www/html/modules
      - drupal-profs:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    restart: always
    deploy:
      replicas: 1
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_password_drupal
      - POSTGRES_USER_FILE=/run/secrets/psql_user_drupal
    secrets:
      - psql_password_drupal
      - psql_user_drupal
    volumes:
      - drupal-data:/var/lib/postgresql/data
    deploy:
      replicas: 1

volumes:
   drupal-data:
   drupal-mods:
   drupal-profs:
   drupal-themes:
   drupal-sites:


secrets:
  psql_user_drupal:
    external: true
  psql_password_drupal:
    external: true
